Sudoku.exe < easy0.txt
Sudoku.exe < easy1.txt
Sudoku.exe < medium2.txt
Sudoku.exe < medium3.txt
Sudoku.exe < hard4.txt
Sudoku.exe < hard5.txt
Sudoku.exe < extreme9.txt
Sudoku.exe < extreme6.txt
Sudoku.exe < extreme7.txt
Sudoku.exe < extreme8.txt
